"""
This script demonstrates how to use the ExampleJSONGenerator to create a valid
JSON object based on a given SQLModel schema. This is useful for generating
test data or few-shot examples for other LLM tasks.
"""

import asyncio
import json
import os
from typing import Optional

from extrai.llm_providers import GeminiClient
from extrai.core import ExampleJSONGenerator
from extrai.core.errors import ExampleGenerationError
from sqlmodel import Field, SQLModel, Relationship


# ======================================================================================
# 1. Define Your Data Models using SQLModel
# ======================================================================================
# The generator will use this schema to understand the desired structure of the JSON.


class ProductSpecs(SQLModel, table=True):
    """Defines the specifications for a product."""

    id: Optional[int] = Field(default=None, primary_key=True)
    display_size: float
    ram_gb: int
    storage_gb: int
    product_id: Optional[int] = Field(default=None, foreign_key="product.id")
    product: Optional["Product"] = Relationship(back_populates="specs")


class Product(SQLModel, table=True):
    """The root model for which we want to generate an example."""

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    price: float
    manufacturer: str
    specs: list["ProductSpecs"] = Relationship(back_populates="product")


# ======================================================================================
# 2. Set up the LLM Client
# ======================================================================================

# IMPORTANT: Set your Gemini API key as an environment variable
# Example: export GEMINI_API_KEY="your_api_key_here"
api_key = os.getenv("GEMINI_API_KEY")
if not api_key:
    raise ValueError(
        "GEMINI_API_KEY environment variable not set. Please set it to your API key."
    )
llm_client = GeminiClient(api_key=api_key)


# ======================================================================================
# 3. Initialize and Run the Example Generator
# ======================================================================================


async def main():
    """
    Initializes the ExampleJSONGenerator, generates a JSON example,
    and prints it to the console.
    """
    print("Initializing Gemini LLM client and example generator...")

    # We want to generate an example for the root model, Product
    generator = ExampleJSONGenerator(llm_client=llm_client, output_model=Product)

    print("Generating example JSON...")
    try:
        # The generator will ask the LLM for an example and validate it against the Product schema.
        example = await generator.generate_example()

        print("\n--- Generated Example JSON ---")
        # Pretty-print the JSON for readability
        parsed_json = json.loads(example)
        print(json.dumps(parsed_json, indent=2))
        print("--------------------------\n")

    except ExampleGenerationError as e:
        print(f"Failed to generate example: {e}")


if __name__ == "__main__":
    asyncio.run(main())

# ======================================================================================
# 4. Expected Output
# ======================================================================================
# The output will be a JSON object that conforms to the Product schema.
# Since the output is generated by an LLM, it will vary with each run.
# Below is an example of what the output might look like.

"""
--- Generated Example JSON ---
[
  {
    "_type": "Product",
    "_temp_id": "product_001",
    "id": 101,
    "name": "Smartphone X",
    "price": 799.99,
    "manufacturer": "TechCorp",
    "specs_ref_ids": [
      "specs_001"
    ]
  },
  {
    "_type": "ProductSpecs",
    "_temp_id": "specs_001",
    "id": 201,
    "display_size": 6.5,
    "ram_gb": 8,
    "storage_gb": 128,
    "product_id": 101,
    "product_ref_id": "product_001"
  }
]
--------------------------
"""
